#!/bin/sh

# arg1: workspace number
# arg2: mointor colors file path

n=$1
monitor_colors_file=$2

printf "(box :class \"module\" :orientation \"h\" :space-evenly true :valign \"center\" :halign \"center\" :spacing 10 :height 30"

for i in $(seq 1 $n); do
    workspace=$i

    # Get the workspace monitor
    monitor=$(hyprctl workspaces | grep -wv 'grep' | grep -w "ID $workspace" | awk -F'[ :]' '{ print $7 }')
    if [ -z "$monitor" ]; then
        monitor="none"
    fi

    # Get the workspace monitor id
    monitor_id=$(hyprctl monitors | grep -w "Monitor $monitor" -A 1 | grep -w 'ID' | awk -F'[ )]' '{ print $4 }')
    if [ -z "$monitor_id" ]; then
        monitor_id="none"
    fi

    # Get the monitor color (trim the leading and trailing whitespace)
    monitor_color=$(grep -oE "$monitor_id[ =]+[0-9a-fA-F]{6}" "$monitor_colors_file" | awk -F'=' '{ print $2 }' | awk '{$1=$1};1')
    if [ -z "$monitor_color" ]; then
        monitor_color="888888"
    fi

    # Print the workspace button
    printf "(button :onclick \"\${setworkspace} $workspace\" :tooltip \"Workspace $workspace\" :style \"color: #$monitor_color;\" {workspace==\"$workspace\" ? \"\" : \"\"} )"
done

printf ")"

exit