#!/bin/sh

# arg1: workspace number
# arg2: mointor colors file path

n=$1
monitor_colors_file=$2

# JSON version

current_workspace (){
    hyprctl activeworkspace | grep -wv 'grep' | grep 'workspace ID' | awk '{ print $3 }'
}

workspace_buttons (){
    for i in $(seq 1 $n); do
        workspace=$i

        monitor=$(hyprctl workspaces | grep -wv 'grep' | grep -w "ID $workspace" | awk -F'[ :]' '{ print $7 }')
        if [ -z "$monitor" ]; then
            monitor="none"
        fi

        monitor_id=$(hyprctl monitors | grep -w "Monitor $monitor" -A 1 | grep -w 'ID' | awk -F'[ )]' '{ print $4 }')
        if [ -z "$monitor_id" ]; then
            monitor_id="none"
        fi

        monitor_color=$(grep -oE "$monitor_id[ =]+[0-9a-fA-F]{6}" "$monitor_colors_file" | awk -F'=' '{ print $2 }' | awk '{$1=$1};1')
        if [ -z "$monitor_color" ]; then
            monitor_color="888888"
        fi

        if [ "$workspace" -eq "$(current_workspace)" ]; then
            printf "(button :onclick \"\${setworkspace} $workspace\" :tooltip \"Workspace $workspace\" :style \"color: #$monitor_color;\" \"\" )"
        else
            printf "(button :onclick \"\${setworkspace} $workspace\" :tooltip \"Workspace $workspace\" :style \"color: #$monitor_color;\" \"\" )"
        fi
    done
}

workspace_buttons_box() {
    printf "(box :class \"module\" :orientation \"h\" :space-evenly true :valign \"center\" :halign \"center\" :spacing 10 :height 30"
    workspace_buttons
    printf ")\n"
}

workspace_buttons_box
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	workspace_buttons_box
done
